# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "AZCI单元测试+覆盖率"
  lane :AZCITests do
    # add actions here: https://docs.fastlane.tools/actions
       run_tests(scheme: "AZCITests",
              clean: true,
              fail_build: false,
              configuration: "Debug",
              output_types: "html,junit",
              # devices: ["iPhone 6s", "iPad Air"],
              devices: ["iPhone 6s"],
              output_files: "AZCITests.html, AZCITests.xml")

       slather(
            output_directory: "fastlane/test_output/slather",
            workspace: "AZCI.xcworkspace",
            html: true,
            scheme: "AZCITests",
            proj: "AZCI.xcodeproj",
            ignore: ["Pods/*"],
            verbose: true,
            # jenkins:true,
            )
  end
end
